language: node_js

node_js:
  - node

script:
  - npm run test
  - npm run test:coveralls

notifications:
  email: false

env:
  global:
    - NODE_ENV=test
    - secure: pXHhFOmdm7/Uquihrpye+oYGZvuG0ZjBNlIHTMEHI7aPQI6M3l0seg1nCdPVimBansLGv+W8psGusTJSvaT0cMN7fyG5E0i9Y3o+6OBFC/jOVgd8eWRQKtcxd6bEqu9k4CDSVlTSVG2v9qty+jMFeos1alDlNXK7GzeyBEjsQ/hkTBJTJFbYfxW6WjHcCcWA5zW7ZhSxDJWJqk/5zJ2c+RKbA1mTAN2pZexKJ/rMuq2usxYqYGuG9iPajTAV3plC95tZ58Yhy6hiUVH+eQoLACtjF20SyGeEpXqYEp5sS/E+Aa/0bFgjE6rr70oohE0ThdB2SDOpJkzXUFly5DnGJUtY+toXq67eiMzhxSUwX8UVM9x0BJCJnkMmVtznKXXIEAXOY0tIR0LzUow71Ljyc3GHl23Hd+A1i6jmdM0PlRZ++M3FEawkCZRE+gjXJgVjFkmVsXjYhNzVVA6S6gO+J1msjlhZ4WuPWHRdk5Y7NZIUGRnPvx80U3Y8Uh3SuGH3Q4B3MtZu8ERAHTHqylD3e2JiVIiFPTi+pW86W1Vq5u7OwOCp3ZG7dMewtZLGrE8gQ1MPha/N1SMrK2xw/Wm+C6rNLOJ5leofRtxk6bx5Opanv/6YHag5lj/aU423gnAAl1n7o1l7ArUsAVdh/GIT0g2ul/I7xqnAr28d6iwnWyY="
