language: node_js

node_js:
  - node

script:
  - npm run test
  - npm run test:coveralls

notifications:
  email: false

env:
  global:
    - NODE_ENV=test
    - secure: j9f6FrbmQwddATpc7eEj54S4hnYkNrlRUWKIE+mPNxELJuAUf7BtH+XpGkOd0cXD6GZfUEx29EgkK8cWmjpP9k91PvGSm9oGrDmGNl5kPkyXltXLpWzhUZxx3JOvOWQaKAX44BfMoTOAJUX8hagr3Vqg4os7g9xIM/QSUrv8fZyUGs605EVypXPkJpOEXsm90mBCIvzbrr14cEl6WNg95HAHoyd8ZlT7mrjQblQ4+y6UDBm5PoVAfSPQuDw6FaB4KmHOlJyMxzNLMqD446nz65WyykkaxU9nZY5qQLPn47TFtXAjGZnIuPvRvg+2fxgeSw9TVpaKJOh/gwvxoXQ0dLRardaw956yH7T7pgld0dq0sE6IAVM/8yEM5bWO6wfG3G6Zx1Bc9NiSzCoEWGHCKt/tr4PGlo1UYFUBJ8+fCD5JUiBHIJggAsin6vj/SndzUFQjM/IFcybUmWYc59SJmC7bjtNVo6SDJ+2hLdNq2yv2DkKWT8vZHUWYll50jvqiwJ2iPr4U2xU5WsDgUq6+r2fusBqZh3aV9hf7dZ7Elw287wXLPqn/OL5CpAQW0k8WL/5SBCg0ThRoGkewZD520CQ1wKqfmajPLzOwdp7xwvpP9uto9+qCBO7nBPi1cu8CgJpmVOuOQxoJmNt6AaEQFCwahJpcgyQXuJAgxyRxdfY=
    - secure: FUrVgiwMNByKIT6PFBqi7Mbg3uAxzmNF/Q3ny6XzAkxTnu25QlO0Ja62d8kN3EEZWU9aMkjTpVXcpROT5L9WLVsdxMaYdv8gYlkXps6xyxTL0M+D0+ALoqv62w3cW6/EtBkqjFyGE/6qIZzlnhHfRgHqh5NxLqCOZj61AHfbFrtNkxSs45YPwkJLPg9ryD1LxW/87yhTIfvZ9hSQAjAg8iGiVYY/UAckNrVjA7wDRSk70MTYkdgCUcXK0k190q5VRlr975OtVMbF3smXtwZUNdGDISARDhBqxQBaBZywI+dPZZukRs/yb+tRW2uVuAaa/nIGdbj97XavscKAOZpnLYr0cnpL/shQPC8SP6bGk/BsKR1P4ep4gHw77mHhB0U9JFAa8f7uy29pUF2ovG3rQ2YvMXkl5KxXPKZ1VGAx/uA2WgLc7w5z9U5jKXt7Q5rGWd+uF3fXgxq4gY1wQ54UOMDgYw2Idf0ByJGBcZidss4fvoZp0z7dR8IPC5j4b9K2LbD0HU9B7B57uWtg9KUOsQwDX2XAgbelwySyIeIldCY/N+b/uNmWr2V80tNwpixMzoTJl3MuHvVhdtZ2puH0oBoKjwUXbye/Y5pxNMErWLUlG/2o2tFCrp+rQwGBdfa//4jU9dJoVP0pznmUZ6v9/REW6HSnzdDhbkXpo5lLWK4=
