language: node_js

node_js:
  - node

script:
  - npm run test
  - npm run test:coverage
  - npm run test:coveralls

notifications:
  email: false

env:
  global:
    - NODE_ENV=test
    - secure: FUrVgiwMNByKIT6PFBqi7Mbg3uAxzmNF/Q3ny6XzAkxTnu25QlO0Ja62d8kN3EEZWU9aMkjTpVXcpROT5L9WLVsdxMaYdv8gYlkXps6xyxTL0M+D0+ALoqv62w3cW6/EtBkqjFyGE/6qIZzlnhHfRgHqh5NxLqCOZj61AHfbFrtNkxSs45YPwkJLPg9ryD1LxW/87yhTIfvZ9hSQAjAg8iGiVYY/UAckNrVjA7wDRSk70MTYkdgCUcXK0k190q5VRlr975OtVMbF3smXtwZUNdGDISARDhBqxQBaBZywI+dPZZukRs/yb+tRW2uVuAaa/nIGdbj97XavscKAOZpnLYr0cnpL/shQPC8SP6bGk/BsKR1P4ep4gHw77mHhB0U9JFAa8f7uy29pUF2ovG3rQ2YvMXkl5KxXPKZ1VGAx/uA2WgLc7w5z9U5jKXt7Q5rGWd+uF3fXgxq4gY1wQ54UOMDgYw2Idf0ByJGBcZidss4fvoZp0z7dR8IPC5j4b9K2LbD0HU9B7B57uWtg9KUOsQwDX2XAgbelwySyIeIldCY/N+b/uNmWr2V80tNwpixMzoTJl3MuHvVhdtZ2puH0oBoKjwUXbye/Y5pxNMErWLUlG/2o2tFCrp+rQwGBdfa//4jU9dJoVP0pznmUZ6v9/REW6HSnzdDhbkXpo5lLWK4=
    - secure: VT61V2qefosXmEVLjjOefwNvwOSzDqHOg0cu+Bj9Z2uJT+gZJhBCdAyy2w7j7AK5tVoNT+e+pmF8EtIJfJtaF5NaKpU1NdAmrOj1VZwscofJQxNTygkCw2kDfw3GDktb7J9J+YnA+026emsS4Ot8UCXUi+CB+iO9Cj+NBpyFA5wSqtdkF06FTdCColHQdZHe3EfgFr4jF+ZOEBN0nZfdjk3TjDrzs9ZPFGmQe34jku2LE9Ek5/VnVTFqHWEJUEKZOw1+JOqEE4DqUv1skdC84fCR04ynrGBnWOWXt8L9XbwcZGTYYOeGKSB17Y2/wbeSWA+ffreMWTiQkxo7zrXav8Xz/HR019L/9bJZ7qm6OufGHDWsD4XmMZ3eoHnu7Pe/l0Jc5WFJ87lTK/iKkxSt3GPLTKzSKo3/i1qIyMtIml+fKMosjFvo67LAHXIP8IKI6LVd5io6Nd5JyZXgo7iASy2pvWdyFGqPNsbghZqXTaTVRTWz30kC5Df/FbiApD6SR3I5n1Q52fMDou2lNuUuhLoic7A863Zs2LEVZL0xp1rjbSoict0kAoFQxieS+dahods67OGn7vwO0Pb/OLZJTUNGGiAGwl/0Iloz+T8dpkSi+6RR83uE9VeDRN2KJO5tvIXSqmQfgrUnFzPfkiwpr6DkNAhJrCp2ZxQL56f0G1w=
