sudo: false

language: node_js

node_js:
  - node

script:
  - npm run test
  - npm run test:coveralls

notifications:
  email: false

env:
  - NODE_ENV=test
  - MONGO_URL_TEST=mongodb+srv://iyansr_admin:PpDjMpuKud4c2Fm1@cluster0-uzhdu.gcp.mongodb.net/test?retryWrites=true&w=majority
